// generated by stringer -type=itemType; DO NOT EDIT

package parse

import "fmt"

const _itemType_name = "itemTextitemLeftMetaitemRightMetaitemBlockitemCloseritemParenthesizedArgumentitemQuotedArgumentitemBracketedArgumentitemDotCommanditemAssignitemIdentifieritemEOFitemError"

var _itemType_index = [...]uint8{0, 8, 20, 33, 42, 52, 77, 95, 116, 130, 140, 154, 161, 170}

func (i itemType) String() string {
	if i < 0 || i+1 >= itemType(len(_itemType_index)) {
		return fmt.Sprintf("itemType(%d)", i)
	}
	return _itemType_name[_itemType_index[i]:_itemType_index[i+1]]
}
